version: '2'
services:
  web:
    build: .
    command: bash -c "npm install node-gyp -g && npm i && npm run dev"
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "4000:80"
    depends_on:
      - postgres
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_PASSWORD: test_doitua
      POSTGRES_USER: test_doitua
      POSTGRES_DB: todos