version: "2"
services:
  node:
    volumes:
      - ./src:/usr/src/app/src
    command: ["npm", "run", "dev"]
  db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=test_doitua
      - POSTGRES_USER=ploy=test_doitua
      - POSTGRES_DB=test_doitua
  lb:
    ports:
      - '4000:80'